[package]
name = "vtf"
description = "Valve Texture format library for Rust"
version = "0.1.1"
license = "MIT"
authors = ["Roman Shishkin <spark@uwtech.org>"]
repository = "https://github.com/roman901/vtf-rs"
edition = "2018"

[dependencies]
image = "0.22.4"